### ISSUE TITLE
Deviation.isFavourite is dead + Deviation method to query deviation itself?

### ISSUE THREAD

**Issue by pbakaus** [danopia/deviantart-difi#4]
Heya,

great work on reverse engineering the API! I've been building a [Stylish script](https://userstyles.org/styles/139441/supercharged-previews) to upgrade the notification center, and I arrived on your wiki because I need to query two things, for every thumbnail on screen:

1. The current users favorite status (on that deviation)
2. Whether the current user has subscribed to the creator of the deviation

Both seems to be supported by the [public API](https://www.deviantart.com/developers/http/v1/20160316/deviation_single/bcc296bdf3b5e40636825a942a514816), which I can't run on DA in a userscript for obvious reasons.

Any way how to get to that info? I had hopes that Deviation.isFavourite (documented in your wiki) would do it, but that API seems to have disappeared. If you're curious, the above APIs would allow me to smartly filter out stuff from group notifications you've already faved or directly subscribed to.

Thanks!
Paul

**Comment by Dediggefedde** [comment]
Hi!
Thanks for the report!

# Favourites
`Deviation::isFavourite` really seems to be removed from DiFi... The buttons for quickly adding a deviation to favourites are now initialized directly in a 
`PortalCore::get_result_thumbs::browse` call it takes the parameters 
"PortalCore","get_result_thumbs",["browse",{"offset":"30","length":"5","mature_filter":"0","view_mode":"full","thumb_mode":"wall","is_mobile":"0","is_frontpage":"1","mixed_output":"0","order":"67108864","results_shown":"10"}]

I couldn't find a different method where it is checked, wether a deviation is already faved or not.
So, for favourites, you will probably have to make a request to the deviation page and grab the info there... I guess the DeviationView::getExtrasHTML, but it will still be a lot of info you won't need. 
In principle, this would be a good solution, if the `RANGE` specifier for http-request would work. There you could request only a certain byte-range of the response, e.g. to get only the favourite-state. However, last time I checked, this header is not supported on deviantart.

# Watching
To check if you watch this user, you can make a request to 
`"Friends","getFriendAttributesAndGroup",["userid"]`
If you watch this person, a html-code for the settings-popup is returned. Otherwise, an String message "This user was not found in your list of friends" will be returned.

**Comment by pbakaus** [comment]
Thanks, that's super helpful! The whole situation about favorites is disappointing, but there's at least a somewhat ugly workaround. I'll try to use both of these and see how far I get. Since this is really useful info, might make sense to include it in the Wiki.

**Comment by DRSDavidSoft** [comment]
We'll be glad if you share your finding with us, it will certainly help future dA developers.
